### ISSUE TITLE
[Feature] Cross line regex

### ISSUE THREAD

**Issue by SmallPepperZ** [variar/klogg#333]
I think that allowing regex highlighting to work across multiple lines would be a nice feature addition. For example, with the below output in a log
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/a/python/package", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/a/code/file", line 141, in cool_function
    print(thisisanundefinedvariable)
NameError: name 'thisisanundefinedvariable' is not defined
```
You could use `Ignoring exception[\s\S]+NameError:.+` to highlight the full traceback with a color you want to use for name errors, instead of using regex that only highlights the last line

**Comment by variar** [comment]
Hi, thanks for sharing an idea. Unfortunately, all string matching in klogg is done line-by-line.  Major rework is needed for multiline matching.

**Comment by variar** [comment]
Merged previous similar request into this one

**Comment by upccjesse** [comment]
Something to consider, that doesn't require a major rewrite to make regex multiline: Specify a starting regex to match your starting line, then have some way to mark this as a "multiline" and have some regex that would either continue the match, or end the match. Two modes;:
1. Match `main pattern` and then continue matching `sub pattern` for each successive line until a non-matching line is found.
2. Match `main pattern' and then match every line until `sub pattern` is detected.

It stays single line, stays compatible with existing highlighter sets, but adds functionality to handle multiline highlights.

**Comment by variar** [comment]
This is indeed a workaround. I feel that most of use-cases should be covered by adding a setting for max lines to look at during matching, and then accumulate that many strings for each match. Need to be carefull when scattering match jobs to multiple threads, but doesn't seem too hard
